export const BGG_CATEGORY_FR: Record<string, string> = {
  "Abstract Strategy":   "Stratégie abstraite",
  "Action / Dexterity":  "Adresse",
  "Adventure":           "Aventure",
  "Age of Reason":       "Siècle des Lumières",
  "American West":       "Far West",
  "Ancient":             "Antiquité",
  "Animals":             "Animaux",
  "Arabian":             "Oriental",
  "Aviation / Flight":   "Aviation",
  "Bluffing":            "Bluff",
  "Card Game":           "Jeu de cartes",
  "Children's Game":     "Jeu enfant",
  "City Building":       "Construction de ville",
  "Civil War":           "Guerre civile",
  "Civilization":        "Civilisation",
  "Collectible Components": "Composants à collectionner",
  "Comic Book / Strip":  "BD / Comics",
  "Deduction":           "Déduction",
  "Dice":                "Dés",
  "Economic":            "Économie",
  "Educational":         "Éducatif",
  "Electronic":          "Électronique",
  "Environmental":       "Environnement",
  "Exploration":         "Exploration",
  "Fantasy":             "Fantastique",
  "Farming":             "Agriculture",
  "Fighting":            "Combat",
  "Horror":              "Horreur",
  "Humor":               "Humour",
  "Industry / Manufacturing": "Industrie",
  "Mafia":               "Mafia",
  "Math":                "Mathématiques",
  "Mature / Adult":      "Adulte",
  "Medieval":            "Médiéval",
  "Memory":              "Mémoire",
  "Miniatures":          "Figurines",
  "Movies / TV / Radio theme": "Cinéma / TV",
  "Murder / Mystery":    "Enquête / Mystère",
  "Music":               "Musique",
  "Mythology":           "Mythologie",
  "Nautical":            "Maritime",
  "Negotiation":         "Négociation",
  "Number":              "Nombres",
  "Party Game":          "Ambiance",
  "Pike and Shot":       "Piques et mousquets",
  "Pirates":             "Pirates",
  "Political":           "Politique",
  "Post-Napoleonic":     "Post-napoléonien",
  "Prehistoric":         "Préhistoire",
  "Print & Play":        "Print & Play",
  "Puzzle":              "Réflexion",
  "Racing":              "Course",
  "Real-time":           "Temps réel",
  "Religious":           "Religieux",
  "Renaissance":         "Renaissance",
  "Science Fiction":     "Science-fiction",
  "Space Exploration":   "Exploration spatiale",
  "Spies / Secret Agents": "Espionnage",
  "Sports":              "Sport",
  "Territory Building":  "Conquête de territoire",
  "Trains":              "Trains",
  "Transportation":      "Transport",
  "Travel":              "Voyage",
  "Trivia":              "Culture générale",
  "Video Game Theme":    "Jeu vidéo",
  "Wargame":             "Wargame",
  "Word Game":           "Jeu de mots",
  "World War I":         "Première Guerre mondiale",
  "World War II":        "Deuxième Guerre mondiale",
  "Zombies":             "Zombies",
  "Cooperative Game":    "Coopératif",
}

export function translateCategory(category: string): string {
  return BGG_CATEGORY_FR[category] ?? category
}
