const CATEGORY_MAP: Record<string, string> = {
  'Abstract Strategy': 'Stratégie abstraite',
  'Action / Dexterity': 'Adresse',
  'Adventure': 'Aventure',
  'American West': 'Far West',
  'Ancient': 'Antiquité',
  'Animals': 'Animaux',
  'Aviation / Flight': 'Aviation',
  'Bluffing': 'Bluff',
  'Book': 'Livre',
  'Card Game': 'Jeu de cartes',
  "Children's Game": 'Jeu enfants',
  'City Building': 'Construction de ville',
  'Collectible Components': 'Éléments à collectionner',
  'Comic Book / Strip': 'Bande dessinée',
  'Deduction': 'Déduction',
  'Dice': 'Dés',
  'Economic': 'Économique',
  'Educational': 'Éducatif',
  'Electronic': 'Électronique',
  'Environmental': 'Environnement',
  'Expansion for Base-game': 'Extension',
  'Exploration': 'Exploration',
  'Fan Expansion': 'Extension fan',
  'Fantasy': 'Fantaisie',
  'Fighting': 'Combat',
  'Horror': 'Horreur',
  'Humor': 'Humour',
  'Mafia': 'Mafia',
  'Math': 'Mathématiques',
  'Mature / Adult': 'Adulte',
  'Medical': 'Médical',
  'Medieval': 'Médiéval',
  'Memory': 'Mémoire',
  'Miniatures': 'Figurines',
  'Movies / TV / Radio theme': 'Cinéma / TV',
  'Murder / Mystery': 'Enquête / Mystère',
  'Music': 'Musique',
  'Mythology': 'Mythologie',
  'Negotiation': 'Négociation',
  'Novel-based': 'Adaptation littéraire',
  'Number': 'Chiffres',
  'Party Game': 'Jeu de soirée',
  'Pirates': 'Pirates',
  'Political': 'Politique',
  'Post-Napoleonic': 'Post-napoléonien',
  'Print & Play': 'Print & Play',
  'Puzzle': 'Puzzle',
  'Racing': 'Course',
  'Real-time': 'Temps réel',
  'Science Fiction': 'Science-fiction',
  'Space Exploration': 'Exploration spatiale',
  'Spies / Secret Agents': 'Espionnage',
  'Sports': 'Sports',
  'Territory Building': 'Contrôle de territoire',
  'Trains': 'Trains',
  'Travel': 'Voyage',
  'Trivia': 'Culture générale',
  'Video Game Theme': 'Jeux vidéo',
  'Wargame': 'Jeu de guerre',
  'Word Game': 'Jeu de mots',
}

/** Decode HTML entities and translate a BGG category to French. */
export function translateCategory(raw: string): string {
  const decoded = raw.replace(/&#0*39;/g, "'").replace(/&amp;/g, '&').replace(/&quot;/g, '"')
  return CATEGORY_MAP[decoded] ?? decoded
}
